language: python
sudo: false
python:
  - "2.6"
  - "2.7"
install:
  - pip install coverage
  - pip install python-coveralls
  - python setup.py install
script:
  - python setup.py test
after_script:
  - coverage run --source skf setup.py test
after_success:
  - coveralls
